name: test-environment
base: core18
version: '0.1'
summary: demo snap environment
description: demo global and app environment vars
grade: stable
confinement: strict

environment:
  TEST_ENV_GLOBAL: "test_env_global"

apps:
   echo:
     command: /bin/echo 
   test-environment:
     command: echo $TEST_ENV_APP
     environment:
       TEST_ENV_APP: test_env_app

parts:
  nil:
    plugin: nil
